// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jgefbXXKo-UPUayZTHubnmvZ2x2l8_M',
    appId: '1:360430158561:web:ea4b3623949ef2fd09ada0',
    messagingSenderId: '360430158561',
    projectId: 'vehicle-tracker-9498c',
    authDomain: 'vehicle-tracker-9498c.firebaseapp.com',
    storageBucket: 'vehicle-tracker-9498c.firebasestorage.app',
    measurementId: 'G-BLCVZWCY0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmoOqiMzC2le2jbiObkkJT8_XSgQNUydY',
    appId: '1:360430158561:android:51f9a3ecdfe14f0d09ada0',
    messagingSenderId: '360430158561',
    projectId: 'vehicle-tracker-9498c',
    storageBucket: 'vehicle-tracker-9498c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9S0ZPoz5F4IAiZ2lTXjixwTQk0RklvXY',
    appId: '1:360430158561:ios:30e521bc03cf573009ada0',
    messagingSenderId: '360430158561',
    projectId: 'vehicle-tracker-9498c',
    storageBucket: 'vehicle-tracker-9498c.firebasestorage.app',
    iosBundleId: 'com.yokoyama-s.truckradar',
  );
}
